### ISSUE TITLE
Add PSO support

### ISSUE THREAD

**Issue by kmpeters** [epics-motor/motorAutomation1#16]
Many of the users of this support will want to send PSO pulses during profile moves.

**Comment by rakaerotech** [comment]
Commit 0b9b7b245b4e4996f0f4f6fb1ae4b58028caeb40 added the ability to execute arbitrary AeroScript commands. This should be used to configure PSO (position synchronized ouput) before running a profile. The [PSO Functions](http://help.aerotech.com/automation1/Content/Concepts/Pso-Functions.htm) page in the Automation1 help describes how to setup PSO using AeroScript. Additionally there are example AeroScript programs on the [AeroScript Example Programs](https://help.aerotech.com/automation1/Content/AeroScript-Example-Programs.htm) page.

**Comment by kmpeters** [comment]
The profileMove support includes triggering:

https://github.com/epics-modules/motor/blob/cc6c6a9b181691e8b04981c64ec99f8a887a937e/motorApp/Db/profileMoveController.template#L42-L68

Users of the profileMove functionality will expect basic triggering to be implemented.

I believe PSO1 functionality would be all that is required.  PSO2 functionality, which is new to me, would likely require custom AeroScripts as well as additional EPICS development.

**Comment by kmpeters** [comment]
@rakaerotech, is there a way to programmatically determine which `Automation1PsoOutputPins` are valid for a controller?
