### ISSUE TITLE
static build error

### ISSUE THREAD

**Issue by LeeYangLBLBCS** [epics-motor/motorAutomation1#18]
I tried static build but got this linker error.
I'm doing it inside "MOTOR".

Installing created dbd file ../../../dbd/automation1.dbd
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE           -D_X86_64_  -DUNIX  -Dlinux      -O3   -Wall      -mtune=generic      -m64  -I. -I../O.Common -I. -I. -I.. -I../../../include/compiler/gcc -I../../../include/os/Linux -I../../../include   -I/opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/include   -I/opt/epics/base-7.0.4/../modules/synApps_6_1_epics7/support/asyn-R4-38/include   -I/opt/epics/base-7.0.4/../modules/synApps_6_1_epics7/support/seq-2-2-7/include   -I/opt/epics/base-7.0.4/../modules/synApps_6_1_epics7/support/busy-R1-7-2/include   -I/opt/epics/base-7.0.4/../modules/synApps_6_1_epics7/support/ipac-2-15/include -I/opt/epics/base-7.0.4/include/compiler/gcc -I/opt/epics/base-7.0.4/include/os/Linux -I/opt/epics/base-7.0.4/include   -I/opt/epics/base-7.0.4/../modules/synApps_6_1_epics7/support/include        -c automation1_registerRecordDeviceDriver.cpp
/usr/bin/g++ -o automation1 -Wl,-Bstatic -L/opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/modules/motorAutomation1/iocs/automation1IOC/lib/linux-x86_64 -L/opt/epics/modules/synApps_6_1_epics7/support/asyn-R4-38/lib/linux-x86_64 -L/opt/epics/modules/synApps_6_1_epics7/support/busy-R1-7-2/lib/linux-x86_64 -L/opt/epics/modules/synApps_6_1_epics7/support/seq-2-2-7/lib/linux-x86_64 -L/opt/epics/base-7.0.4/lib/linux-x86_64 -L/opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/lib/linux-x86_64 -Wl,-rpath,/opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/modules/motorAutomation1/iocs/automation1IOC/lib/linux-x86_64 -Wl,-rpath,/opt/epics/modules/synApps_6_1_epics7/support/asyn-R4-38/lib/linux-x86_64 -Wl,-rpath,/opt/epics/modules/synApps_6_1_epics7/support/busy-R1-7-2/lib/linux-x86_64 -Wl,-rpath,/opt/epics/modules/synApps_6_1_epics7/support/seq-2-2-7/lib/linux-x86_64 -Wl,-rpath,/opt/epics/base-7.0.4/lib/linux-x86_64 -Wl,-rpath,/opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/lib/linux-x86_64           -rdynamic -m64         automation1_registerRecordDeviceDriver.o automation1Main.o    -lAutomation1 -lmotor -lasyn -lbusy -lseq -lpv -ldbRecStd -ldbCore -lca -lCom -Wl,-Bdynamic  -lpthread   -lreadline -lm -lrt -ldl -lgcc
/usr/bin/ld: /opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/lib/linux-x86_64/libAutomation1.a(Automation1MotorController.o): in function `Automation1MotorController::~Automation1MotorController()':
Automation1MotorController.cpp:(.text+0x1e): undefined reference to `Automation1_DataCollectionConfig_Destroy'
/usr/bin/ld: Automation1MotorController.cpp:(.text+0x2a): undefined reference to `Automation1_Disconnect'
/usr/bin/ld: /opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/lib/linux-x86_64/libAutomation1.a(Automation1MotorController.o): in function `Automation1MotorController::logApiError(int, char const*)':
Automation1MotorController.cpp:(.text+0x3f3): undefined reference to `Automation1_GetLastError'
/usr/bin/ld: Automation1MotorController.cpp:(.text+0x402): undefined reference to `Automation1_GetLastErrorMessage'
/usr/bin/ld: /opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/lib/linux-x86_64/libAutomation1.a(Automation1MotorController.o): in function `Automation1MotorController::abortProfile()':
Automation1MotorController.cpp:(.text+0x46a): undefined reference to `Automation1_Task_ProgramStop'
/usr/bin/ld: /opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/lib/linux-x86_64/libAutomation1.a(Automation1MotorController.o): in function `Automation1MotorController::executeProfile()':
Automation1MotorController.cpp:(.text+0x521): undefined reference to `Automation1_DataCollection_Start'
/usr/bin/ld: Automation1MotorController.cpp:(.text+0x52d): undefined reference to `Automation1_DataCollection_Stop'
/usr/bin/ld: Automation1MotorController.cpp:(.text+0x545): undefined reference to `Automation1_Task_ProgramRun'
/usr/bin/ld: /opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/lib/linux-x86_64/libAutomation1.a(Automation1MotorController.o): in function `Automation1MotorController::readbackProfile()':
Automation1MotorController.cpp:(.text+0x66b): undefined reference to `Automation1_DataCollection_GetStatus'
/usr/bin/ld: Automation1MotorController.cpp:(.text+0x683): undefined reference to `Automation1_DataCollection_GetStatus'
/usr/bin/ld: Automation1MotorController.cpp:(.text+0x773): undefined reference to `Automation1_DataCollection_GetResults'
/usr/bin/ld: Automation1MotorController.cpp:(.text+0x80d): undefined reference to `Automation1_DataCollection_GetAxisResults'
/usr/bin/ld: Automation1MotorController.cpp:(.text+0x8f4): undefined reference to `Automation1_DataCollection_GetAxisResults'
/usr/bin/ld: Automation1MotorController.cpp:(.text+0xbd3): undefined reference to `Automation1_DataCollection_GetAxisResults'
/usr/bin/ld: /opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/lib/linux-x86_64/libAutomation1.a(Automation1MotorController.o): in function `Automation1MotorController::Automation1MotorController(char const*, char const*, int, double, double)':
Automation1MotorController.cpp:(.text+0xd2a): undefined reference to `Automation1_ConnectWithHost'
/usr/bin/ld: Automation1MotorController.cpp:(.text+0xd59): undefined reference to `Automation1_Controller_IsRunning'
/usr/bin/ld: Automation1MotorController.cpp:(.text+0xdec): undefined reference to `Automation1_Controller_Start'
/usr/bin/ld: /opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/lib/linux-x86_64/libAutomation1.a(Automation1MotorController.o): in function `Automation1MotorController::poll()':
Automation1MotorController.cpp:(.text+0xf85): undefined reference to `Automation1_DataCollection_GetStatus'
/usr/bin/ld: Automation1MotorController.cpp:(.text+0xfa3): undefined reference to `Automation1_Task_GetStatus'
/usr/bin/ld: /opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/lib/linux-x86_64/libAutomation1.a(Automation1MotorController.o): in function `Automation1MotorController::writeOctet(asynUser*, char const*, unsigned long, unsigned long*)':
Automation1MotorController.cpp:(.text+0x1164): undefined reference to `Automation1_Command_Execute'
/usr/bin/ld: /opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/lib/linux-x86_64/libAutomation1.a(Automation1MotorController.o): in function `Automation1MotorController::writeInt32(asynUser*, int)':
Automation1MotorController.cpp:(.text+0x11fd): undefined reference to `Automation1_Command_AcknowledgeAll'
/usr/bin/ld: /opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/lib/linux-x86_64/libAutomation1.a(Automation1MotorController.o): in function `Automation1MotorController::buildProfile()':
Automation1MotorController.cpp:(.text+0x1725): undefined reference to `Automation1_DataCollectionConfig_ClearAllDataSignals'
/usr/bin/ld: Automation1MotorController.cpp:(.text+0x1766): undefined reference to `Automation1_DataCollectionConfig_AddAxisDataSignal'
/usr/bin/ld: Automation1MotorController.cpp:(.text+0x17a1): undefined reference to `Automation1_DataCollectionConfig_AddAxisDataSignal'
/usr/bin/ld: Automation1MotorController.cpp:(.text+0x18b9): undefined reference to `Automation1_DataCollectionConfig_Create'
/usr/bin/ld: Automation1MotorController.cpp:(.text+0x1f23): undefined reference to `Automation1_Files_WriteBytes'
/usr/bin/ld: /opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/lib/linux-x86_64/libAutomation1.a(Automation1MotorAxis.o): in function `Automation1MotorAxis::~Automation1MotorAxis()':
Automation1MotorAxis.cpp:(.text+0x1e): undefined reference to `Automation1_StatusConfig_Destroy'
/usr/bin/ld: /opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/lib/linux-x86_64/libAutomation1.a(Automation1MotorAxis.o): in function `Automation1MotorAxis::Automation1MotorAxis(Automation1MotorController*, int)':
Automation1MotorAxis.cpp:(.text+0x81): undefined reference to `Automation1_StatusConfig_Create'
/usr/bin/ld: Automation1MotorAxis.cpp:(.text+0x97): undefined reference to `Automation1_StatusConfig_AddAxisStatusItem'
/usr/bin/ld: Automation1MotorAxis.cpp:(.text+0xad): undefined reference to `Automation1_StatusConfig_AddAxisStatusItem'
/usr/bin/ld: Automation1MotorAxis.cpp:(.text+0xc3): undefined reference to `Automation1_StatusConfig_AddAxisStatusItem'
/usr/bin/ld: Automation1MotorAxis.cpp:(.text+0xd9): undefined reference to `Automation1_StatusConfig_AddAxisStatusItem'
/usr/bin/ld: Automation1MotorAxis.cpp:(.text+0xef): undefined reference to `Automation1_StatusConfig_AddAxisStatusItem'
/usr/bin/ld: /opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/lib/linux-x86_64/libAutomation1.a(Automation1MotorAxis.o):Automation1MotorAxis.cpp:(.text+0x105): more undefined references to `Automation1_StatusConfig_AddAxisStatusItem' follow
/usr/bin/ld: /opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/lib/linux-x86_64/libAutomation1.a(Automation1MotorAxis.o): in function `Automation1MotorAxis::logError(char const*)':
Automation1MotorAxis.cpp:(.text+0x160): undefined reference to `Automation1_GetLastError'
/usr/bin/ld: Automation1MotorAxis.cpp:(.text+0x170): undefined reference to `Automation1_GetLastErrorMessage'
/usr/bin/ld: /opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/lib/linux-x86_64/libAutomation1.a(Automation1MotorAxis.o): in function `Automation1MotorAxis::move(double, int, double, double, double)':
Automation1MotorAxis.cpp:(.text+0x28e): undefined reference to `Automation1_Command_SetupAxisRampValue'
/usr/bin/ld: Automation1MotorAxis.cpp:(.text+0x2cb): undefined reference to `Automation1_Command_MoveAbsolute'
/usr/bin/ld: Automation1MotorAxis.cpp:(.text+0x316): undefined reference to `Automation1_Command_MoveIncremental'
/usr/bin/ld: /opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/lib/linux-x86_64/libAutomation1.a(Automation1MotorAxis.o): in function `Automation1MotorAxis::home(double, double, double, int)':
Automation1MotorAxis.cpp:(.text+0x3af): undefined reference to `Automation1_Command_SetupAxisRampValue'
/usr/bin/ld: Automation1MotorAxis.cpp:(.text+0x3d1): undefined reference to `Automation1_Command_HomeAsync'
/usr/bin/ld: /opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/lib/linux-x86_64/libAutomation1.a(Automation1MotorAxis.o): in function `Automation1MotorAxis::moveVelocity(double, double, double)':
Automation1MotorAxis.cpp:(.text+0x49d): undefined reference to `Automation1_Command_SetupAxisRampValue'
/usr/bin/ld: Automation1MotorAxis.cpp:(.text+0x4ca): undefined reference to `Automation1_Command_MoveFreerun'
/usr/bin/ld: /opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/lib/linux-x86_64/libAutomation1.a(Automation1MotorAxis.o): in function `Automation1MotorAxis::stop(double)':
Automation1MotorAxis.cpp:(.text+0x55f): undefined reference to `Automation1_Command_Abort'
/usr/bin/ld: /opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/lib/linux-x86_64/libAutomation1.a(Automation1MotorAxis.o): in function `Automation1MotorAxis::setPosition(double)':
Automation1MotorAxis.cpp:(.text+0x5ee): undefined reference to `Automation1_Command_PositionOffsetSet'
/usr/bin/ld: /opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/lib/linux-x86_64/libAutomation1.a(Automation1MotorAxis.o): in function `Automation1MotorAxis::setClosedLoop(bool)':
Automation1MotorAxis.cpp:(.text+0x66d): undefined reference to `Automation1_Command_Enable'
/usr/bin/ld: Automation1MotorAxis.cpp:(.text+0x696): undefined reference to `Automation1_Command_Disable'
/usr/bin/ld: /opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/lib/linux-x86_64/libAutomation1.a(Automation1MotorAxis.o): in function `Automation1MotorAxis::poll(bool*)':
Automation1MotorAxis.cpp:(.text+0x713): undefined reference to `Automation1_Status_GetResults'
/usr/bin/ld: Automation1MotorAxis.cpp:(.text+0x7d4): undefined reference to `Automation1_Parameter_GetAxisValue'
collect2: error: ld returned 1 exit status
make[5]: *** [/opt/epics/base-7.0.4/configure/RULES_BUILD:213: automation1] Error 1
make[5]: Leaving directory '/opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/modules/motorAutomation1/iocs/automation1IOC/automation1App/src/O.linux-x86_64'
make[4]: *** [/opt/epics/base-7.0.4/configure/RULES_ARCHS:58: install.linux-x86_64] Error 2
make[4]: Leaving directory '/opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/modules/motorAutomation1/iocs/automation1IOC/automation1App/src'
make[3]: *** [/opt/epics/base-7.0.4/configure/RULES_DIRS:85: src.install] Error 2
make[3]: Leaving directory '/opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/modules/motorAutomation1/iocs/automation1IOC/automation1App'
make[2]: *** [/opt/epics/base-7.0.4/configure/RULES_DIRS:85: automation1App.install] Error 2
make[2]: Leaving directory '/opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/modules/motorAutomation1/iocs/automation1IOC'
make[1]: *** [/opt/epics/base-7.0.4/configure/RULES_DIRS:85: automation1IOC.install] Error 2
make[1]: Leaving directory '/opt/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/modules/motorAutomation1/iocs'
make: *** [/opt/epics/base-7.0.4/configure/RULES_DIRS:85: iocs.install] Error 2

**Comment by MarkRivers** [comment]
> Aerteoch will need to provide static libraries (.a) for the static build to succeed.

That is not true. It can use .dll files, but they must be added as PROD_SYS_LIBS or LIB_SYS_LIBS. There are many examples of doing this in areaDetector.

**Comment by MarkRivers** [comment]
See this file:
https://github.com/areaDetector/ADAndor3/blob/master/andor3App/src/Makefile

**Comment by MarkRivers** [comment]
This may be a better example:
https://github.com/areaDetector/ADSpinnaker/blob/master/iocs/spinnakerIOC/spinnakerApp/src/Makefile

**Comment by kmpeters** [comment]
Does the PROD_SYS_LIBS_Linux approach include the code from the .so in the static binary or does the mostly-static binary still depend on the vendor .so files?

**Comment by anjohnson** [comment]
@kmpeters The PROD_SYS_LIBS approach to a .so has to create a dynamic link to the .so (it can't pull in the code from the .so), so the resulting executable will still have to find the vendor's library at runtime.

If an EPICS build target is configured with `STATIC_BUILD=YES` the build will search for lib*.a files for everything listed in the LIBS or equivalent variables, and will fail the build if it doesn't find them (i.e. if only a .so is available for anything in the LIBS list). The build system does not do that kind of a search for libraries in the `SYS_LIBS` variables though, which is why this fix works. If however you only set `SHARED_LIBRARIES=NO` without also setting `STATIC_BUILD=YES` then the build will not create .so files for the libraries that it builds, but will happily use either a .so or a .a library from LIBS (preferring the .so if both are present). Note that this does not apply to Windows builds, the `STATIC_BUILD` and `SHARED_LIBRARIES` settings are exclusive there.

Thus on Linux an alternative to setting `PROD_SYS_LIBS` might be to set `STATIC_BUILD=NO` in the Makefile where the executable gets built, and then either will be acceptable.

**Comment by MarkRivers** [comment]
It still depends on vendor .so files I believe.

**Comment by kmpeters** [comment]
Thanks @anjohnson.  That is helpful.

**Comment by kmpeters** [comment]
@LeeYangLBLBCS, how are you configuring motorAutomation1 to build statically?

**Comment by LeeYangLBLBCS** [comment]
I changed CONFIG_SITE in epics base/config:
SHARED_LIBRARIES=NO
STATIC_BUILD=YES

then I tried various settings in IOC/src/Makefile to include automation1's library files:
PROD_LIBS
PROD_SYS_LIBS
etc.
Always ended up with linker errors I showed.

**Comment by anjohnson** [comment]
@LeeYangLBLBCS Try changing the `base/configure/CONFIG_SITE` setting to `STATIC_BUILD=NO` (leaving `SHARED_LIBRARIES=NO`); you shouldn't need to rebuild Base or the other support modules although doing that should still be possible, just rebuild the final application, using `PROD_LIBS` for the vendor's libraries. Make sure they are listed in the right order in that variable, when linking to static libraries the linker only makes a single pass through each library, the order in `PROD_LIBS` controls the order of the `-l` options on the link command-line.

**Comment by kmpeters** [comment]
I have confirmed that this change eliminates the build problems:
```diff
$ git diff
diff --git a/iocs/automation1IOC/automation1App/src/Makefile b/iocs/automation1IOC/automation1App/src/Makefile
index 7db248c..86290cb 100644
--- a/iocs/automation1IOC/automation1App/src/Makefile
+++ b/iocs/automation1IOC/automation1App/src/Makefile
@@ -11,6 +11,9 @@ include $(TOP)/configure/CONFIG
 #=============================
 # Build the IOC application
 
+#
+STATIC_BUILD = NO
+
 PROD_IOC = automation1
 # automation1.dbd will be created and installed
 DBD += automation1.dbd
@@ -38,8 +41,9 @@ else
 automation1compiler_DIR += $(MOTOR)/bin/$(EPICS_HOST_ARCH)
 automation1c_DIR += $(MOTOR)/bin/$(EPICS_HOST_ARCH)
 endif
-Automation1_LIBS += automation1compiler
-Automation1_LIBS += automation1c
+#
+automation1_LIBS += automation1compiler
+automation1_LIBS += automation1c
 
 # Add all the support libraries needed by this IOC
 automation1_LIBS += Automation1
```
I succeeded at building motorAutomation1 against base-7.0.6.1 with the default config (``SHARED_LIBRARIES=YES`` and ``STATIC_BUILD=NO``) and with @LeeYangLBLBCS's original base config (``SHARED_LIBRARIES=NO`` and ``STATIC_BUILD=YES``)

It also removes the two lines that started with the ``Automation1_`` prefix, rather than the ``automation1_`` prefix used everywhere else in the file.

**Comment by kmpeters** [comment]
I can see that the IOC's static binary only depends on the automation1 & system libraries:
```bash
$ ldd ../../bin/linux-x86_64/automation1 
	linux-vdso.so.1 (0x00007ffd901db000)
	libautomation1compiler.so => /home/user/epics/motor-devel/current/motorAutomation1-static/bin/linux-x86_64/libautomation1compiler.so (0x00007f4b21910000)
	libautomation1c.so => /home/user/epics/motor-devel/current/motorAutomation1-static/bin/linux-x86_64/libautomation1c.so (0x00007f4b21279000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f4b21059000)
	libreadline.so.7 => /lib64/libreadline.so.7 (0x00007f4b20e0a000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f4b20c02000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f4b209fe000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f4b20669000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f4b202e7000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f4b200cf000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f4b1fd0c000)
	libsodium.so.23 => /lib64/libsodium.so.23 (0x00007f4b1fab4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4b218b0000)
	libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007f4b1f887000)
```
The IOC that was built against base with the standard config depends on EPICS libraries as well as additional system libraries:
```bash
$ ldd ../../bin/linux-x86_64/automation1 
	linux-vdso.so.1 (0x00007ffc66b6e000)
	libautomation1compiler.so => /home/user/epics/motor-devel/current/motorAutomation1/bin/linux-x86_64/libautomation1compiler.so (0x00007f34dbdbd000)
	libautomation1c.so => /home/user/epics/motor-devel/current/motorAutomation1/bin/linux-x86_64/libautomation1c.so (0x00007f34db726000)
	libAutomation1.so => /home/user/epics/motor-devel/current/motorAutomation1/lib/linux-x86_64/libAutomation1.so (0x00007f34db519000)
	libmotor.so => /home/user/epics/motor-devel/current/motor/lib/linux-x86_64/libmotor.so (0x00007f34db2f8000)
	libasyn.so => /home/user/epics/motor-devel/support/asyn-R4-42/lib/linux-x86_64/libasyn.so (0x00007f34db059000)
	libbusy.so => /home/user/epics/motor-devel/support/busy-R1-7-3/lib/linux-x86_64/libbusy.so (0x00007f34dae4f000)
	libseq.so => /home/user/epics/motor-devel/support/seq-2-2-9/lib/linux-x86_64/libseq.so (0x00007f34dac3f000)
	libpv.so => /home/user/epics/motor-devel/support/seq-2-2-9/lib/linux-x86_64/libpv.so (0x00007f34daa3b000)
	libdbRecStd.so.3.21.0 => /home/user/epics/base-7.0.6.1/lib/linux-x86_64/libdbRecStd.so.3.21.0 (0x00007f34da7f5000)
	libdbCore.so.3.21.0 => /home/user/epics/base-7.0.6.1/lib/linux-x86_64/libdbCore.so.3.21.0 (0x00007f34da560000)
	libca.so.4.14.1 => /home/user/epics/base-7.0.6.1/lib/linux-x86_64/libca.so.4.14.1 (0x00007f34da2fa000)
	libCom.so.3.21.0 => /home/user/epics/base-7.0.6.1/lib/linux-x86_64/libCom.so.3.21.0 (0x00007f34da084000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f34d9cef000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f34d996d000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f34d9755000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f34d9392000)
	libsodium.so.23 => /lib64/libsodium.so.23 (0x00007f34d913a000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f34d8f1a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f34dbd5d000)
	libreadline.so.7 => /lib64/libreadline.so.7 (0x00007f34d8ccb000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f34d8ac3000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f34d88bf000)
	libtirpc.so.3 => /lib64/libtirpc.so.3 (0x00007f34d868c000)
	libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007f34d845f000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f34d820a000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f34d7f1f000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f34d7d08000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f34d7b04000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f34d78f3000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f34d76ef000)
	libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f34d7209000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f34d6ff0000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f34d6dc6000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f34d6baf000)
	libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007f34d692b000)
```

**Comment by kmpeters** [comment]
@LeeYangLBLBCS, if you don't object, I'll create a pull request to resolve this issue before moving on to #17
