### ISSUE TITLE
Remove 1ms/pt profileMove limitation

### ISSUE THREAD

**Issue by kmpeters** [epics-motor/motorAutomation1#25]
Profile moves are currently limited to 1ms/pt:

https://github.com/epics-motor/motorAutomation1/blob/92896c702801f381b7c4f9680de4183451d66308/README.md?plain=1#L23-L26

Remove this restriction, possibly at the expense of data collection.

**Comment by kmpeters** [comment]
Questions for Aerotech: 

1. The Automation1 documentation implies that data collection can happen at rates slower than 1kHz, but the Automation1_DataCollectionConfig_Create only accepts an enum that lacks slower options.  How should slower data collection rates be selected?

2. Automation1_Task_ProgramRun, which is called by the executeProfile method, doesn't wait for program to complete, so the controller's poll method relies on the data collection status, which doesn't work for profiles that use times per point significantly greater than 1ms.  Could Automation1_Task_GetStatus be used to determine whether or not epics_profile_move.ascript is done executing, instead of relying on the data collection status?

**Comment by kmpeters** [comment]
> Can you give more context for this use-case? Why are time between points in a profile slower than 1 kHz? Is the time between each point consistent or variable? Can the profile be interpolated up to 1 kHz (either by the user, EPICS, or the Automation1 motor driver)?

For some of the non-linear moves that were done with the Ensemble, the number of points used to describe the motion profile was only 200 for a 100-second move.  A small number of points was chosen to minimize the time it took to send the positions to the Ensemble controller.  It takes much less time to send the data to the Automation1 controller, so the number could be increased, however, 100k points is excessive for a profile that was adequately defined by 200 points.

The maximum number of profile-move points is fixed when an EPICS IOC starts.  The profile move's time-per-point is frequently changed and varies greatly, which changes the number of data collection samples at 1kHz.

If the driver is modified so that the number of data collection samples equals the total move time (s) * 1000 (samples/s), can the number of waypoints in the profile move be significantly fewer than the number of data collection samples?  Is there a requirement that the data collection sample period equal the time for each segment of the profile move or was requiring 1ms/pt just a simple way of ensuring the move and data collection end at the same time?

**Comment by jilavsky** [comment]
Let me - as end user - just point out, that during routine operations our flyscans were as fast as 30 seconds and as slow as 360 seconds and anything in between. User choice which depends on quality of data needed (angular range does not change). 
Not sure about the hardware, but trajectory with 360k triplets of points seems bit excessive :-)

**Comment by jilavsky** [comment]
There is no deceleration between points, the stage moves in relatively constant speed between points. It is not critical the speed is on any curved speed profile or linear between waypoints - as long as the three stages moving at once stay in coordinated move. The speed varies by multiple decades. Not sure exactly what HLe does when executing the trajectory, but 200 waypoints with user defined time between points (same time between every two points) has served really well. 

The way we collect data is 
a. Execute coordinated trajectory of three stages 
b. Independently have driver provide PSO pulses according to array of positions (typically 8000 angles) which trigger our data counter system. We do not use waypoints trajectory for anything, we map the 8000 data collected in our counting system to 8000 PSO angles uploaded to the driver. 
These 8000 positions are heavily non linearly spaced in angle and do not necessarily have the same time between each two points.  
As explanation - we measure intensity which changes by 9 decades and need to collect data spaced angularly on log-scale with steps starting from <0.00001 degree and ending with steps ~0.01 degree. We are trying to optimize statistics per point and that is in this  setup really difficult. There is nothing linear in this system.
We have provided Aerotech with example of both waypoint trajectory and PSO pulse positions and were told this method of data collection is doable. We were provided with output which was tested in acceptance testing as proof that rotation stage can deliver. This was in order specification as required delivery capability.  What we need is epics driver being able to perform this data collection.

**Comment by kmpeters** [comment]
It looks like I can use the default axis velocity if the motor record velocity is zero:
```
2023/06/28 12:18:39.648 Automation1MotorController:executeProfile: axis = 6, motorRecVelocity = 0.000000, defaultCoordVelocity = 50.000000, defaultVelocity = 2.000000                                                                                                                  
```
The default coordinated velocity for this axis exceeds the max velocity and results in a fault, which is probably why the LinearMove command failed when I didn't specify a velocity.
