### ISSUE TITLE
The issue when I run IOC

### ISSUE THREAD

**Issue by PeiyuQuan** [epics-motor/motorAutomation1#32]
Hello

This is an issue when i run IOC. Is it from the controller? 
When I ping IP address, it works.

Peiyu Quan

quan@PC98545:~/epics/support/motor/modules/motorAutomation1/iocs/automation1IOC/iocBoot/iocAutomation1$ ../../bin/linux-x86_64/automation1 st.cmd
#!../../bin/linux-x86_64/automation1
< envPaths
epicsEnvSet("IOC","iocAutomation1")
epicsEnvSet("TOP","/home/quan/epics/support/motor/modules/motorAutomation1/iocs/automation1IOC")
epicsEnvSet("MOTOR","/home/quan/epics/support/motor")
epicsEnvSet("ASYN","/home/quan/epics/support/asyn")
epicsEnvSet("SNCSEQ","/home/quan/epics/support/seq-2-2-9")
epicsEnvSet("BUSY","/home/quan/epics/support/busy")
epicsEnvSet("IPAC","/home/quan/epics/support/ipac")
epicsEnvSet("LUA","/home/quan/epics/support/lua")
epicsEnvSet("MODBUS","/home/quan/epics/support/modbus")
epicsEnvSet("EPICS_BASE","/home/quan/epics/base")
epicsEnvSet("SUPPORT","/home/quan/epics/support")
## Register all support components
dbLoadDatabase("../../dbd/automation1.dbd")
automation1_registerRecordDeviceDriver(pdbbase)
## motorUtil (allstop & alldone)
dbLoadRecords("/home/quan/epics/support/motor/db/motorUtil.db", "P=automation1:")
## Automation1 Support
< automation1.cmd
# Automation1CreateController(
#   const char* portName,    # asyn port name
#   const char* hostName,    # hostname or ip address
#   int numAxes,
#   int movingPollPeriod,    # unit: milliseconds
#   int idlePollPeriod,      # unit: milliseconds
#   int commandExecuteTask,  # default task index: 1
#   int profileMoveTask)     # default task index: 2
Automation1CreateController("Automation1", "192.168.62.88:12200", 4, 100, 1000, 1, 2)
2024/02/06 12:38:16.018 [Automation1 Driver] Could not connect to Automation1 controller. API Error: 23 "Cannot connect to the controller because an unknown error occurred."
2024/02/06 12:38:16.018 [Automation1 Driver] Could not determine if Automation1 controller is running. API Error: 96007 "The controller argument cannot be null."
2024/02/06 12:38:16.018 [Automation1 Driver] Could not start Automation1 controller. API Error: 96007 "The controller argument cannot be null."
# traceError and traceIODriver
#!asynSetTraceMask("Automation1", 0, 0x9)
# traceIOAscii
#!asynSetTraceIOMask("Automation1", 0, 0x1)
Automation1CreateProfile("Automation1", 2000)
2024/02/06 12:38:16.019 Driver: Automation1. Function Message: Poll failed.. Axis: 0. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.019 Driver: Automation1. Function Message: Poll failed.. Axis: 1. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.019 Driver: Automation1. Function Message: Poll failed.. Axis: 2. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.019 Driver: Automation1. Function Message: Poll failed.. Axis: 3. API Error Code: 96007. API Error Message: The controller argument cannot be null.
dbLoadTemplate "motor.substitutions.automation1"
dbLoadRecords("/home/quan/epics/support/asyn/db/asynRecord.db", "P=BL62:iXI4:, R=asyn1, PORT=Automation1, ADDR=0, OMAX=256, IMAX=256")
iocInit
Starting iocInit
############################################################################
############################################################################
2024/02/06 12:38:16.119 Driver: Automation1. Function Message: Poll failed.. Axis: 0. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.119 Driver: Automation1. Function Message: Poll failed.. Axis: 1. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.119 Driver: Automation1. Function Message: Poll failed.. Axis: 2. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.119 Driver: Automation1. Function Message: Poll failed.. Axis: 3. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.219 Driver: Automation1. Function Message: Poll failed.. Axis: 0. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.219 Driver: Automation1. Function Message: Poll failed.. Axis: 1. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.219 Driver: Automation1. Function Message: Poll failed.. Axis: 2. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.219 Driver: Automation1. Function Message: Poll failed.. Axis: 3. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.320 Driver: Automation1. Function Message: Poll failed.. Axis: 0. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.320 Driver: Automation1. Function Message: Poll failed.. Axis: 1. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.320 Driver: Automation1. Function Message: Poll failed.. Axis: 2. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.320 Driver: Automation1. Function Message: Poll failed.. Axis: 3. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.420 Driver: Automation1. Function Message: Poll failed.. Axis: 0. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.420 Driver: Automation1. Function Message: Poll failed.. Axis: 1. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.420 Driver: Automation1. Function Message: Poll failed.. Axis: 2. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.420 Driver: Automation1. Function Message: Poll failed.. Axis: 3. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.520 Driver: Automation1. Function Message: Poll failed.. Axis: 0. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.520 Driver: Automation1. Function Message: Poll failed.. Axis: 1. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.520 Driver: Automation1. Function Message: Poll failed.. Axis: 2. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.520 Driver: Automation1. Function Message: Poll failed.. Axis: 3. API Error Code: 96007. API Error Message: The controller argument cannot be null.
iocRun: All initialization complete
## motorUtil (allstop & alldone)
motorUtilInit("automation1:")
##
# This IOC does not use save/restore, so set values of some PVs
dbpf("Auto1:m1.RTRY", "0")
PV 'Auto1:m1.RTRY' not found
dbpf("Auto1:m1.TWV", "0.1")
PV 'Auto1:m1.TWV' not found
dbpf("Auto1:m2.RTRY", "0")
PV 'Auto1:m2.RTRY' not found
dbpf("Auto1:m2.TWV", "0.1")
PV 'Auto1:m2.TWV' not found
dbpf("Auto1:m3.RTRY", "0")
PV 'Auto1:m3.RTRY' not found
dbpf("Auto1:m3.TWV", "0.1")
PV 'Auto1:m3.TWV' not found
dbpf("Auto1:m4.RTRY", "0")
PV 'Auto1:m4.RTRY' not found
dbpf("Auto1:m4.TWV", "0.1")
PV 'Auto1:m4.TWV' not found
# Boot complete
2024/02/06 12:38:16.621 Driver: Automation1. Function Message: Poll failed.. Axis: 0. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.621 Driver: Automation1. Function Message: Poll failed.. Axis: 1. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.621 Driver: Automation1. Function Message: Poll failed.. Axis: 2. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.621 Driver: Automation1. Function Message: Poll failed.. Axis: 3. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.722 Driver: Automation1. Function Message: Poll failed.. Axis: 0. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.722 Driver: Automation1. Function Message: Poll failed.. Axis: 1. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.722 Driver: Automation1. Function Message: Poll failed.. Axis: 2. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.722 Driver: Automation1. Function Message: Poll failed.. Axis: 3. API Error Code: 96007. API Error Message: The controller argument cannot be null.
epics> 2024/02/06 12:38:16.822 Driver: Automation1. Function Message: Poll failed.. Axis: 0. API Error Code: 96007. API Error Message: The controller argument cannot be null.
2024/02/06 12:38:16.822 Driver: Automation1. Function Message: Poll failed.. Axis: 1. API Error Code: 96007. API Error Message: The controller argument cannot be null.

**Comment by rakaerotech** [comment]
The hostname should _not_ include the port number, specify only the IP address or host name (i.e. "192.168.62.88").

**Comment by PeiyuQuan** [comment]
I used iXI4 with four-channels send pulse to stepper motor. I have made stage files for each motor/stage. 
But When I set controller to output clock & direction mode, It show "the device is not compatible with an electrical device that output Clock & Direction". But from manual, iXI4 should support this mode.
Could you tell me where is that issue?
![iXI4](https://github.com/epics-motor/motorAutomation1/assets/41603034/7dd692ab-6b9b-433f-8026-0ebd15039ff6)

**Comment by PeiyuQuan** [comment]
I have fixed this issue. I set "stepper" before, it should be set "stepper driver".
Thank you
